"""
delta-chat · src/delta/report.py
══════════════════════════════════════════════════════════════════════════════
Delta report renderer — outputs both machine-parseable JSON and
human-readable Markdown/HTML from a DeltaReport.

The rendered report is:
  1. Written to disk as {run_id}/delta_report.json + delta_report.md
  2. Returned as a ReportBundle for immediate use
  3. Indexed into ChromaDB as a first-class retrievable source for chat
══════════════════════════════════════════════════════════════════════════════
"""
from __future__ import annotations

import json
import os
from collections import defaultdict
from dataclasses import dataclass
from typing import Optional

from jinja2 import Environment, BaseLoader

from src.canonical.model import DeltaItem, DeltaReport
from src.config import get_settings
from src.observability.logging import get_logger

log = get_logger(__name__)
settings = get_settings()

# ─────────────────────────────────────────────────────────────────────────────
# Output bundle
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ReportBundle:
    report: DeltaReport
    json_path: str
    markdown_path: str
    markdown_text: str
    json_text: str


# ─────────────────────────────────────────────────────────────────────────────
# Markdown template
# ─────────────────────────────────────────────────────────────────────────────

_MD_TEMPLATE = """\
# Delta Report — {{ report.pid_a }} → {{ report.pid_b }}

**Generated:** {{ report.generated_at }}
**Run ID:** {{ report.run_id }}

---

## Summary

| Metric | Value |
|---|---|
| Total Changes | **{{ s.total_changes }}** |
| Added | {{ s.added }} |
| Removed | {{ s.removed }} |
| Modified | {{ s.modified }} |
| Avg Confidence | {{ "%.2f"|format(s.avg_confidence) }} |
| Low-Confidence Items | {{ s.low_confidence_count }} |

### Changes by Element Type

{% for etype, count in s.by_element_type.items() %}
- **{{ etype }}**: {{ count }}
{% endfor %}

---

## Changes by Sheet / Page

{% for page_idx, page_items in pages.items() %}
### Sheet {{ page_idx + 1 }}{% if page_labels.get(page_idx) %} — {{ page_labels[page_idx] }}{% endif %}  ({{ page_items|length }} change{{ 's' if page_items|length != 1 else '' }})

{% for item in page_items %}
#### [{{ item.change_type|upper }}] {{ item.element_type }} — `{{ item.delta_id }}`

**Confidence:** {{ "%.2f"|format(item.confidence) }} | **Method:** {{ item.alignment_method }}

{{ item.description }}

{% if item.old_value and item.new_value %}
| | Value |
|---|---|
| **Before (A)** | `{{ item.old_value[:200] }}` |
| **After (B)** | `{{ item.new_value[:200] }}` |
{% elif item.old_value %}
**Removed value:** `{{ item.old_value[:200] }}`
{% elif item.new_value %}
**Added value:** `{{ item.new_value[:200] }}`
{% endif %}

{% if item.location_a %}📍 **PID A** page {{ item.location_a.page_index + 1 }}{% if item.location_a.page_label %} ({{ item.location_a.page_label }}){% endif %} — bbox: ({{ "%.0f"|format(item.location_a.bbox.x0) }}, {{ "%.0f"|format(item.location_a.bbox.y0) }}){% endif %}
{% if item.location_b %}📍 **PID B** page {{ item.location_b.page_index + 1 }}{% if item.location_b.page_label %} ({{ item.location_b.page_label }}){% endif %} — bbox: ({{ "%.0f"|format(item.location_b.bbox.x0) }}, {{ "%.0f"|format(item.location_b.bbox.y0) }}){% endif %}

---
{% endfor %}
{% endfor %}

## Low-Confidence Items (confidence < 0.70)

{% set low_conf = report.items | selectattr("confidence", "lt", 0.70) | list %}
{% if low_conf %}
| delta_id | type | change | confidence | description |
|---|---|---|---|---|
{% for item in low_conf %}
| `{{ item.delta_id }}` | {{ item.element_type }} | {{ item.change_type }} | {{ "%.2f"|format(item.confidence) }} | {{ item.description[:80] }} |
{% endfor %}
{% else %}
*No low-confidence items.*
{% endif %}

---
*Generated by delta-chat · Document Delta & Grounded Chat*
"""


class DeltaReportRenderer:
    """Renders a DeltaReport to JSON + Markdown and writes to disk."""

    def render(self, report: DeltaReport, output_dir: str) -> ReportBundle:
        """Render and write report files. Returns a ReportBundle."""
        os.makedirs(output_dir, exist_ok=True)

        json_text = self._render_json(report)
        markdown_text = self._render_markdown(report)

        json_path = os.path.join(output_dir, "delta_report.json")
        md_path = os.path.join(output_dir, "delta_report.md")

        with open(json_path, "w", encoding="utf-8") as f:
            f.write(json_text)
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(markdown_text)

        log.info(
            "report.rendered",
            run_id=report.run_id,
            json_path=json_path,
            md_path=md_path,
            total_changes=report.summary.get("total_changes", 0),
        )
        return ReportBundle(
            report=report,
            json_path=json_path,
            markdown_path=md_path,
            markdown_text=markdown_text,
            json_text=json_text,
        )

    def _render_json(self, report: DeltaReport) -> str:
        """Serialize report to indented JSON (excluding element_a/b for size)."""
        data = report.model_dump(
            exclude={"items": {"__all__": {"element_a", "element_b"}}}
        )
        return json.dumps(data, indent=2, default=str)

    def _render_markdown(self, report: DeltaReport) -> str:
        """Render Markdown via Jinja2 template."""
        # Group items by primary page
        pages: dict[int, list[DeltaItem]] = defaultdict(list)
        page_labels: dict[int, Optional[str]] = {}
        for item in report.items:
            pi = item.primary_page_index
            pages[pi].append(item)
            if item.location_b:
                page_labels[pi] = item.location_b.page_label
            elif item.location_a:
                page_labels[pi] = item.location_a.page_label

        env = Environment(loader=BaseLoader())
        template = env.from_string(_MD_TEMPLATE)
        return template.render(
            report=report,
            s=report.summary,
            pages=dict(sorted(pages.items())),
            page_labels=page_labels,
        )

    def render_summary_for_indexing(self, report: DeltaReport) -> list[str]:
        """
        Split report into chunks for ChromaDB indexing.
        Each chunk = one page's worth of changes + metadata prefix.
        This ensures citation granularity at the page level.
        """
        chunks: list[str] = []

        # Chunk 1: summary block
        s = report.summary
        chunks.append(
            f"Delta Report Summary [{report.run_id}]: "
            f"PID A={report.pid_a}, PID B={report.pid_b}. "
            f"Total changes: {s['total_changes']} "
            f"(added: {s['added']}, removed: {s['removed']}, modified: {s['modified']}). "
            f"By type: {json.dumps(s['by_element_type'])}."
        )

        # Chunks 2+: one per page
        pages: dict[int, list[DeltaItem]] = defaultdict(list)
        for item in report.items:
            pages[item.primary_page_index].append(item)

        for pi, items in sorted(pages.items()):
            lines = [f"Delta changes on page {pi + 1} [{report.run_id}]:"]
            for item in items:
                lines.append(
                    f"  [{item.change_type.upper()}] {item.element_type} "
                    f"(delta_id={item.delta_id}, confidence={item.confidence:.2f}): "
                    f"{item.description}"
                )
                if item.old_value:
                    lines.append(f"    Before: {item.old_value[:120]}")
                if item.new_value:
                    lines.append(f"    After: {item.new_value[:120]}")
            chunks.append("\n".join(lines))

        return chunks
